Rails.application.routes.draw do
  get 'payments/index'
  get 'payments/show'
  get 'payments/new'
  get 'payments/create'
  get 'payments/edit'
  get 'payments/update'
  get 'payments/destroy'
  get 'taxes/index'
  get 'taxes/show'
  get 'taxes/new'
  get 'taxes/create'
  get 'taxes/edit'
  get 'taxes/update'
  get 'taxes/destroy'
  get 'cart_items/index'
  get 'cart_items/show'
  get 'cart_items/new'
  get 'cart_items/create'
  get 'cart_items/edit'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'carts/index'
  get 'carts/show'
  get 'carts/new'
  get 'carts/create'
  get 'carts/edit'
  get 'carts/update'
  get 'carts/destroy'
  get 'admins/index'
  get 'admins/show'
  get 'admins/new'
  get 'admins/create'
  get 'admins/edit'
  get 'admins/update'
  get 'admins/destroy'
  get 'addresses/index'
  get 'addresses/show'
  get 'addresses/new'
  get 'addresses/create'
  get 'addresses/edit'
  get 'addresses/update'
  get 'addresses/destroy'
  get 'order_items/index'
  get 'order_items/show'
  get 'order_items/new'
  get 'order_items/create'
  get 'order_items/edit'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'orders/create'
  get 'orders/edit'
  get 'orders/update'
  get 'orders/destroy'
  get 'products/index'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  get 'customers/index'
  get 'customers/show'
  get 'customers/new'
  get 'customers/create'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end
